# Retrieve all articles (= pasal) of Omnibus Law
PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?pasalVersion ?text WHERE {
  <http://example.org/legal/document/uu/2020/11> legal:pasal ?pasal .
  ?pasal legal:versi ?pasalVersion .
  ?pasalVersion legal:pasalVersionHasRawText ?text .
} LIMIT 3