# Retrieve all articles (= pasal) of Omnibus Law
PREFIX lex2kg-o: <https://example.org/lex2kg/ontology/>

SELECT ?pasalVersion ?text WHERE {
  <https://example.org/lex2kg/uu/2020/11> lex2kg-o:pasal ?pasal .
  ?pasal lex2kg-o:versi ?pasalVersion .
  ?pasalVersion lex2kg-o:teks ?text .
} 
ORDER BY ?pasal ?text
LIMIT 3