# Retrieve all articles (= pasal) of Omnibus Law
PREFIX lex2kg-o: <https://example.org/lex2kg/ontology/>

SELECT ?pasal ?text WHERE {
  { 
    SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
      <https://example.org/lex2kg/uu/2020/11> lex2kg-o:pasal ?pasal .
      ?pasal lex2kg-o:versi ?pasalVersion .
    } GROUP BY ?pasal 
  }
  ?latestPasalVersion lex2kg-o:teks ?text
} 
ORDER BY ?pasal ?text
LIMIT 3