PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?pasal ?latestPasalVersion
WHERE {
  SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) 
  WHERE {
    <http://example.org/legal/document/uu/2020/11> legal:documentHasPasal ?pasal .
    ?pasal legal:pasalHasPasalVersion ?pasalVersion .
  }
  GROUP BY ?pasal
}