# Retrieve all articles (= pasal) of Omnibus Law
PREFIX legal: <http://example.org/lex2kg/ontology/>

SELECT ?pasal ?text WHERE {
  { 
    SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
      <http://example.org/lex2kg/uu/2020/11> legal:pasal ?pasal .
      ?pasal legal:versi ?pasalVersion .
    } GROUP BY ?pasal 
  }
  ?latestPasalVersion legal:teks ?text
} 
ORDER BY ?pasal ?text
LIMIT 3