# What is the textual content of Article (or Pasal) 2 Subsection (or Ayat) 1 of Omnibus Law?
PREFIX o: <https://example.org/lex2kg/ontology/>

SELECT ?x ?text WHERE {
  ?pasal o:bagianDari+ <https://example.org/lex2kg/uu/2020/11>.
  ?pasal o:nomor 2 .
  ?x o:bagianDari* ?pasal .
  ?x o:nomor 1 .
  ?x o:teks ?text .
}
ORDER BY ?x ?text
LIMIT 3