# What is the textual content of Article (or Pasal) 2 Subsection (or Ayat) 1 of Omnibus Law?
PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?x ?text WHERE {
  ?pasal legal:bagianDari+ <http://example.org/legal/peraturan/uu/2020/11>.
  ?pasal legal:nomor 2 .
  ?x legal:bagianDari* ?pasal .
  ?x legal:nomor 1 .
  ?x legal:teks ?text .
}
ORDER BY ?x ?text
LIMIT 3