# Which are the articles of Chapter 2 (Bab 2) of Omnibus Law?
PREFIX lex2kg-o: <https://example.org/lex2kg/ontology/>

SELECT ?pasal ?text WHERE {
  {
    SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
      ?bab lex2kg-o:bagianDari+ <https://example.org/lex2kg/uu/2020/11>.
      ?bab lex2kg-o:nomor 2 .
      ?pasal lex2kg-o:bagianDari+ ?bab .
      ?pasal lex2kg-o:versi ?pasalVersion .
    } GROUP BY ?pasal
  }
  ?latestPasalVersion lex2kg-o:teks ?text
} 
ORDER BY ?pasal ?text
LIMIT 3