# Which are the articles of Chapter 2 (Bab 2) of Omnibus Law?
PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?pasal ?text WHERE {
  {
    SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
      ?bab legal:partOf+ <http://example.org/legal/document/uu/2020/11>.
      ?bab legal:nomor 2 .
      ?pasal legal:partOf+ ?bab .
      ?pasal legal:versi ?pasalVersion .
    } GROUP BY ?pasal
  }
  ?latestPasalVersion legal:pasalVersionHasRawText ?text
} LIMIT 3