# Get subsections (= ayat) containing "kompensasi" and "buruh" that are added by Omnibus Law into other laws
PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?ayat ?text WHERE {
  ?insertingPoint legal:bagianDari+ <http://example.org/legal/peraturan/uu/2020/11> .
  ?insertingPoint legal:menyisipkan ?insertedPasalVersion .
  ?ayat legal:bagianDari+ ?insertedPasalVersion .
  ?ayat legal:teks ?text
  FILTER REGEX(str(?text), "kompensasi")
  FILTER REGEX(str(?text), "buruh")
} LIMIT 3