PREFIX legal: <http://example.org/legal/ontology/>

SELECT 
	?ayat
  ?text
WHERE {
  {
    SELECT 
    	?pasal 
    	(MAX(?pasalVersion) as ?latestPasalVersion) 
    WHERE {
      ?pasal legal:partOf+ <http://example.org/legal/document/uu/2020/11>.
      ?pasal legal:pasalHasPasalVersion ?pasalVersion .
    }
    GROUP BY ?pasal
  }
  ?insertingPoint legal:partOf+ ?latestPasalVersion .
  ?insertingPoint legal:pointInsertPasalVersion ?insertedPasalVersion .
  ?ayat legal:partOf+ ?insertedPasalVersion .
  ?ayat legal:ayatHasRawText ?text
  FILTER REGEX(str(?text), "kompensasi")
  FILTER REGEX(str(?text), "buruh")
}
ORDER BY
	?ayat
