# Get subsections (= ayat) containing "kompensasi" and "buruh" that are added by Omnibus Law into other laws
PREFIX lex2kg-o: <https://example.org/lex2kg/ontology/>

SELECT ?ayat ?text WHERE {
  {
    SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
      ?pasal lex2kg-o:bagianDari+ <https://example.org/lex2kg/uu/2020/11>.
      ?pasal lex2kg-o:versi ?pasalVersion .
    } GROUP BY ?pasal
  }
  ?insertingPoint lex2kg-o:bagianDari+ ?latestPasalVersion .
  ?insertingPoint lex2kg-o:menyisipkan ?insertedPasalVersion .
  ?ayat lex2kg-o:bagianDari+ ?insertedPasalVersion .
  ?ayat lex2kg-o:teks ?text
  FILTER REGEX(str(?text), "kompensasi")
  FILTER REGEX(str(?text), "buruh")
} LIMIT 3
