# Retrieve components of Omnibus Law that insert (= menyisipkan) articles (= pasal) into Labor Law (UU Ketenagakerjaan) and show the textual content of the articles
PREFIX lex2kg-o: <https://example.org/lex2kg/ontology/>

SELECT ?insertingPoint ?insertedPasalVersion ?text WHERE {
  ?insertingPoint lex2kg-o:bagianDari+ <https://example.org/lex2kg/uu/2020/11>.
  ?insertingPoint lex2kg-o:menyisipkan ?insertedPasalVersion .
  ?insertedPasalVersion lex2kg-o:bagianDari+ <https://example.org/lex2kg/uu/2003/13> .
  ?insertedPasalVersion lex2kg-o:teks ?text .
}
ORDER BY ?insertingPoint ?insertedPasalVersion
LIMIT 3
