# Retrieve components of Omnibus Law that insert (= menyisipkan) articles (= pasal) into Labor Law (UU Ketenagakerjaan) and show the textual content of the articles
PREFIX legal: <http://example.org/lex2kg/ontology/>

SELECT ?insertingPoint ?insertedPasalVersion ?text WHERE {
  {
    SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
      ?pasal legal:bagianDari+ <http://example.org/lex2kg/uu/2020/11>.
      ?pasal legal:versi ?pasalVersion .
    } GROUP BY ?pasal
  }
  ?insertingPoint legal:bagianDari+ ?latestPasalVersion .
  ?insertingPoint legal:menyisipkan ?insertedPasalVersion .
  ?insertedPasalVersion legal:bagianDari+ <http://example.org/lex2kg/uu/2003/13> .
  ?insertedPasalVersion legal:teks ?text .
}
ORDER BY ?insertingPoint ?insertedPasalVersion
LIMIT 3
