# Retrieve components of Omnibus Law that insert (= menyisipkan) articles (= pasal) into Labor Law (UU Ketenagakerjaan) and show the textual content of the articles
PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?insertingPoint ?insertedPasalVersion ?text WHERE {
  {
    SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
      ?pasal legal:partOf+ <http://example.org/legal/document/uu/2020/11>.
      ?pasal legal:versi ?pasalVersion .
    } GROUP BY ?pasal
  }
  ?insertingPoint legal:partOf+ ?latestPasalVersion .
  ?insertingPoint legal:menyisipkan ?insertedPasalVersion .
  ?insertedPasalVersion legal:partOf+ <http://example.org/legal/document/uu/2003/13> .
  ?insertedPasalVersion legal:pasalVersionHasRawText ?text .
}
LIMIT 3
