# Get components of Omnibus Law that amend (= mengubah) articles in Labor Law and compare the textual content of the old vs. new articles
PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?updatingPointt ?updatedPasal ?text ?version
WHERE {
  {
    SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
      ?pasal legal:partOf+ <http://example.org/legal/document/uu/2020/11>.
      ?pasal legal:versi ?pasalVersion .
    } GROUP BY ?pasal
  }
  ?updatingPointt legal:partOf+ <http://example.org/legal/document/uu/2020/11>.
  ?updatingPointt legal:mengubah ?updatedPasalVersion .
  ?updatedPasal legal:versi ?updatedPasalVersion .
  <http://example.org/legal/document/uu/2003/13> legal:pasal ?updatedPasal .
  ?updatedPasal legal:versi ?allPasalVersion .
  ?allPasalVersion legal:pasalVersionHasRawText ?text .
  ?allPasalVersion legal:tanggal ?version .
}
LIMIT 3
