# Get components of Omnibus Law that amend (= mengubah) articles in Labor Law and compare the textual content of the old vs. new articles
PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?insertingPoint ?insertedPasal ?version ?text WHERE {
  {
    SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
      ?pasal legal:partOf+ <http://example.org/legal/document/uu/2020/11>.
      ?pasal legal:versi ?pasalVersion .
    } GROUP BY ?pasal
  }
  ?insertingPoint legal:partOf+ ?latestPasalVersion .
  ?insertingPoint legal:menyisipkan ?insertedPasalVersion .
  ?insertedPasalVersion legal:partOf+ <http://example.org/legal/document/uu/2003/13> .
  ?insertedPasal legal:versi ?insertedPasalVersion .
  ?insertedPasal legal:versi ?allPasalVersion .
  ?allPasalVersion legal:pasalVersionHasRawText ?text .
  ?allPasalVersion legal:tanggal ?version .
}
LIMIT 3
