PREFIX legal: <http://example.org/legal/ontology/>

SELECT 
	?deletingPoint 
	?deletedPasal
WHERE {
  {
    SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) 
    WHERE {
      ?pasal legal:partOf+ <http://example.org/legal/document/uu/2020/11>.
      ?pasal legal:pasalHasPasalVersion ?pasalVersion .
    }
    GROUP BY ?pasal
  }
  ?deletingPoint legal:partOf+ ?latestPasalVersion .
  ?deletingPoint legal:pointDeletePasalVersion ?deletedPasalVersion .
  ?deletedPasal legal:pasalHasPasalVersion ?deletedPasalVersion .
  
}
ORDER BY 
	?deletingPoint
	?deletedPasal
