# Give me components of Omnibus Law that remove (= menghapus) articles in Labor Law and show the textual content of the removed articles
PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?deletingPoint ?deletedPasal ?version ?text WHERE {
  {
    SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
      ?pasal legal:partOf+ <http://example.org/legal/document/uu/2020/11>.
      ?pasal legal:pasalHasPasalVersion ?pasalVersion .
    } GROUP BY ?pasal
  }
  ?deletingPoint legal:partOf+ ?latestPasalVersion .
  ?deletingPoint legal:pointDeletePasalVersion ?deletedPasalVersion .
  ?deletedPasal legal:pasalHasPasalVersion ?deletedPasalVersion .
  <http://example.org/legal/document/uu/2003/13> legal:documentHasPasal ?deletedPasal .
  ?deletedPasal legal:pasalHasPasalVersion ?allPasalVersion .
  ?allPasalVersion legal:pasalVersionHasRawText ?text .
  ?allPasalVersion legal:pasalVersionHasCreatedTimeEpoch ?version .
}
LIMIT 3
