# How many are insertions, amendments, and removals of other laws in Omnibus Law?
PREFIX lex2kg-o: <https://example.org/lex2kg/ontology/>

SELECT ?type (COUNT(*) AS ?jumlah) WHERE {
  {
    ?point lex2kg-o:bagianDari+ <https://example.org/lex2kg/uu/2020/11> .
    ?point lex2kg-o:menghapus ?pasal .
    BIND("menghapus" AS ?type)
  } UNION {
    ?point lex2kg-o:bagianDari+ <https://example.org/lex2kg/uu/2020/11> .
    ?point lex2kg-o:menyisipkan ?pasal .
    BIND("menyisipkan" AS ?type)
  } UNION {
    ?point lex2kg-o:bagianDari+ <https://example.org/lex2kg/uu/2020/11> .
    ?point lex2kg-o:mengubah ?pasal .
    BIND("mengubah" AS ?type)
  }
} GROUP BY ?type
LIMIT 3
