# How many are insertions, amendments, and removals of other laws in Omnibus Law?
PREFIX lex2kg-o: <https://example.org/lex2kg/ontology/>

SELECT ?type (COUNT(*) AS ?jumlah) WHERE {
  {
    {
      SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
        ?pasal lex2kg-o:bagianDari+ <https://example.org/lex2kg/uu/2020/11>.
        ?pasal lex2kg-o:versi ?pasalVersion .
      } GROUP BY ?pasal
    }
    ?deletingPoint lex2kg-o:bagianDari+ ?latestPasalVersion .
    ?deletingPoint lex2kg-o:menghapus ?deletedPasalVersion .
    BIND("menghapus" AS ?type)
  }
  UNION {
    {
      SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
        ?pasal lex2kg-o:bagianDari+ <https://example.org/lex2kg/uu/2020/11>.
        ?pasal lex2kg-o:versi ?pasalVersion .
      } GROUP BY ?pasal
    }
    ?deletingPoint lex2kg-o:bagianDari+ ?latestPasalVersion .
    ?deletingPoint lex2kg-o:menyisipkan ?deletedPasalVersion .
    BIND("menyisipkan" AS ?type)
  } UNION {
    {
      SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
        ?pasal lex2kg-o:bagianDari+ <https://example.org/lex2kg/uu/2020/11>.
        ?pasal lex2kg-o:versi ?pasalVersion .
      } GROUP BY ?pasal
    }
    ?deletingPoint lex2kg-o:bagianDari+ ?latestPasalVersion .
    ?deletingPoint lex2kg-o:mengubah ?deletedPasalVersion .
    BIND("mengubah" AS ?type)
  }
} GROUP BY ?type
LIMIT 3
