# How many are insertions, amendments, and removals of other laws in Omnibus Law?
PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?type (COUNT(*) AS ?jumlah) WHERE {
  {
    {
      SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
        ?pasal legal:bagianDari+ <http://example.org/legal/peraturan/uu/2020/11>.
        ?pasal legal:versi ?pasalVersion .
      } GROUP BY ?pasal
    }
    ?deletingPoint legal:bagianDari+ ?latestPasalVersion .
    ?deletingPoint legal:menghapus ?deletedPasalVersion .
    BIND("menghapus" AS ?type)
  }
  UNION {
    {
      SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
        ?pasal legal:bagianDari+ <http://example.org/legal/peraturan/uu/2020/11>.
        ?pasal legal:versi ?pasalVersion .
      } GROUP BY ?pasal
    }
    ?deletingPoint legal:bagianDari+ ?latestPasalVersion .
    ?deletingPoint legal:menyisipkan ?deletedPasalVersion .
    BIND("menyisipkan" AS ?type)
  } UNION {
    {
      SELECT ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
        ?pasal legal:bagianDari+ <http://example.org/legal/peraturan/uu/2020/11>.
        ?pasal legal:versi ?pasalVersion .
      } GROUP BY ?pasal
    }
    ?deletingPoint legal:bagianDari+ ?latestPasalVersion .
    ?deletingPoint legal:mengubah ?deletedPasalVersion .
    BIND("mengubah" AS ?type)
  }
} GROUP BY ?type
LIMIT 3
