PREFIX legal: <http://example.org/legal/ontology/>

SELECT DISTINCT ?pasalVersion ?text WHERE {
  ?pasalVersion legal:partOf+ <http://example.org/legal/document/uu/2020/11>.
  ?pasalVersion legal:pasalVersionHasRawText ?text .
  FILTER NOT EXISTS {
    ?point legal:partOf+ ?pasalVersion . 
    ?point a legal:Point .
    { ?point legal:pointUpdatePasalVersion ?amendedPasalVersion }
    UNION { ?point legal:pointInsertPasalVersion ?amendedPasalVersion } 
    UNION { ?point legal:pointDeletePasalVersion ?amendedPasalVersion }
  }
}
LIMIT 3