# Get articles of Omnibus Law that are not about updating (= insertions/amendments/removals) other laws
PREFIX legal: <http://example.org/legal/ontology/>

SELECT DISTINCT ?pasalVersion ?text WHERE {
  ?pasalVersion legal:partOf+ <http://example.org/legal/document/uu/2020/11>.
  ?pasalVersion legal:pasalVersionHasRawText ?text .
  FILTER NOT EXISTS {
    ?point legal:partOf+ ?pasalVersion . 
    ?point a legal:Point .
    { ?point legal:mengubah ?amendedPasalVersion }
    UNION { ?point legal:menyisipkan ?amendedPasalVersion } 
    UNION { ?point legal:menghapus ?amendedPasalVersion }
  }
}
LIMIT 3
