PREFIX legal: <http://example.org/legal/ontology/>

SELECT DISTINCT ?pasalVersion WHERE {
  ?point legal:partOf+ <http://example.org/legal/document/uu/2020/11>.
  ?point legal:pointDeletePasalVersion ?pasalVersion .
  ?pasalVersion legal:partOf+ ?document .
  ?document legal:documentHasYear ?year
  FILTER(?year > 2001)
}
