# Retrieve all subsections inserted by Omnibus Law into other laws and *optionally* the citations occurring in those subsections
PREFIX lex2kg-o: <https://example.org/lex2kg/ontology/>

SELECT ?ayat ?text ?citation WHERE {
  ?insertingPoint lex2kg-o:bagianDari+ <https://example.org/lex2kg/uu/2020/11>.
  ?insertingPoint lex2kg-o:menyisipkan ?insertedPasalVersion .
  ?ayat lex2kg-o:bagianDari+ ?insertedPasalVersion .
  ?ayat lex2kg-o:teks ?text .
  ?ayat lex2kg-o:teks ?textRef .
  OPTIONAL {?textRef lex2kg-o:merujuk ?citation}
}
ORDER BY ?ayat ?text ?citation
LIMIT 3