# tampilkan 10 dokumen yang pernah diamandemen
PREFIX o: <https://example.org/lex2kg/ontology/>

SELECT DISTINCT ?doc ?amenderDoc
WHERE {
  ?doc a o:Peraturan .
  ?pasal o:bagianDari ?doc .
  ?pasal o:versi ?pasalVersion .
  ?amender o:mengubah ?pasalVersion .
  ?amender o:bagianDari* ?amenderDoc .
  ?amenderDoc a o:Peraturan
}
ORDER BY ?doc ?amenderDoc
LIMIT 10