# Which law has the most number of updates (= insertions/amendments/removals) by Omnibus Law? For that law, show the most recent version taking into account the updates by Omnibus Law!
PREFIX legal: <http://example.org/legal/ontology/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?law ?numOfUpdates ?pasal (MAX(?pasalVersion) as ?latestPasalVersion) WHERE {
  {
    SELECT ?law (COUNT(*) AS ?numOfUpdates) WHERE {
      ?point legal:partOf+ <http://example.org/legal/document/uu/2020/11> .
      { ?point legal:mengubah ?amendedPasalVersion }
      UNION { ?point legal:menyisipkan ?amendedPasalVersion }
      UNION { ?point legal:menghapus ?amendedPasalVersion }
      ?amendedPasalVersion legal:partOf+ ?law .
      ?law a legal:Document .
    } GROUP BY ?law
  }
  ?pasal legal:partOf+ ?law .
  ?pasal legal:versi ?pasalVersion .
}
GROUP BY ?law ?numOfUpdates ?pasal
ORDER BY DESC (?numOfUpdates)
LIMIT 3
