# tampilkan semua UU yang disahkan setelah 10 Oktober 2019
PREFIX legal: <http://example.org/legal/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT *
WHERE {
  ?legalDoc legal:disahkanPada ?date .
  FILTER ( ?date >= "2019-10-10"^^xsd:date )
}
ORDER BY ?legalDoc
