# tampilkan legal document beserta yang ditimbangnya (menimbang)
PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?doc ?menimbangDoc
WHERE {
  ?doc legal:menimbang ?menimbang .
  ?menimbangText legal:partOf* ?menimbang .
  ?menimbangText legal:merujuk ?menimbangDoc .
  ?menimbangDoc a legal:Document
}
ORDER BY ?doc
LIMIT 10
