# select 10 legal document dengan pasal terbanyak
PREFIX legal: <http://example.org/lex2kg/ontology/>

SELECT ?doc (COUNT(?pasal) as ?pasalCount)
WHERE {
  ?doc a legal:Peraturan .
  ?doc legal:pasal ?pasal .
}
GROUP BY ?doc
ORDER BY DESC(?pasalCount)
LIMIT 10
