# tampilkan 10 dokumen yang pernah diamandemen
PREFIX legal: <http://example.org/legal/ontology/>

SELECT DISTINCT ?doc ?amenderDoc
WHERE {
  ?doc a legal:Peraturan .
  ?pasal legal:bagianDari ?doc .
  ?pasal legal:versi ?pasalVersion .
  ?amender legal:mengubah ?pasalVersion .
  ?amender legal:bagianDari* ?amenderDoc .
  ?amenderDoc a legal:Peraturan
}
ORDER BY ?doc ?amenderDoc
LIMIT 10