# tampilkan 10 dokumen yang pernah diamandemen
PREFIX legal: <http://example.org/legal/ontology/>

SELECT DISTINCT ?doc ?amenderDoc
WHERE {
  ?doc a legal:Document .
  ?pasal legal:partOf ?doc .
  ?pasal legal:versi ?pasalVersion .
  ?amender legal:mengubah ?pasalVersion .
  ?amender legal:partOf* ?amenderDoc .
  ?amenderDoc a legal:Document
}
LIMIT 10