# tampilkan 10 tempat disahkan paling banyak
PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?location (COUNT(?doc) as ?docCount)
WHERE {
  ?doc legal:documentHasDisahkanLocation ?location
}
GROUP BY ?location
ORDER BY DESC (?docCount)