# tampilkan 10 dokumen paling banyak ditimbang
PREFIX lex2kg-o: <https://example.org/lex2kg/ontology/>

SELECT ?menimbangDoc (COUNT(?doc) as ?penimbangDocCount)
WHERE {
  ?doc lex2kg-o:menimbang ?menimbang .
  ?menimbangText lex2kg-o:bagianDari* ?menimbang .
  ?menimbangText lex2kg-o:merujuk ?menimbangDoc .
  ?menimbangDoc a lex2kg-o:Peraturan
}
GROUP BY ?menimbangDoc
ORDER BY DESC (?penimbangDocCount)
LIMIT 10
