# tampilkan 10 dokumen paling banyak ditimbang
PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?menimbangDoc (COUNT(?doc) as ?penimbangDocCount)
WHERE {
  ?doc legal:menimbang ?menimbang .
  ?menimbang legal:daftarHuruf ?menimbangPointSet .
  ?menimbangPointSet legal:huruf ?menimbangPoint .
  ?menimbangPoint legal:segmen ?menimbangText .
  ?menimbangText legal:merujuk ?menimbangDoc .
  ?menimbangDoc a legal:Document
}
GROUP BY ?menimbangDoc
ORDER BY DESC (?penimbangDocCount)
LIMIT 10
