
PREFIX legal: <http://example.org/legal/ontology/>

SELECT ?bab ?title
WHERE {
  ?doc a legal:Document .
  ?bab legal:partOf* ?doc .
  ?bab a legal:Bab .
  ?bab legal:babHasTitle ?title.
  FILTER REGEX(str(?title), "KERJA")
}
LIMIT 10
