# Count triples about document change
PREFIX lex2kg-o: <https://example.org/lex2kg/ontology/>

SELECT (COUNT (*) as ?countResult) WHERE {
  ?s lex2kg-o:mengubah|lex2kg-o:menghapus|lex2kg-o:menyisipkan ?o
} 
