# Count triples with citation to non existing law
PREFIX legal: <http://example.org/lex2kg/ontology/>

SELECT (COUNT(*) as ?countResult) WHERE {
  {
    SELECT ?s ?o WHERE {
      ?s legal:merujuk ?o .
    }
  } MINUS {
    SELECT ?s ?o WHERE {
      ?s legal:merujuk ?o .
      ?s legal:bagianDari* ?doc .
      ?o legal:bagianDari* ?doc .
      ?doc a legal:Peraturan .
    }
  } MINUS {
    SELECT ?s ?o WHERE {
      ?s legal:merujuk ?o .
      ?s (legal:bagianDari|^legal:mengingat|^legal:menimbang)* ?sdoc .
      ?o legal:bagianDari* ?odoc .
      ?sdoc a legal:Peraturan .
      ?odoc a legal:Peraturan .
      FILTER (?sdoc != ?odoc)
    }
  }
} 
