PREFIX legal: <http://example.org/legal/ontology/>
SELECT ?pasal ?ayat ?text
WHERE{
  ?pasal legal:hasKey 7 .
  ?pasal a legal:Pasal .
  ?ayat legal:hasKey 2 .
  ?ayat legal:partOf ?pasal .
  ?ayat legal:hasText ?text
}
ORDER BY ?pasal ?ayat ?text